name: flutter_task_app
description: A simple task management Flutter app using Firebase Auth & Firestore with Riverpod.
publish_to: 'none' 

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  intl: ^0.18.0   
  flutter_svg: ^2.0.9
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^5.0.0
  equatable: ^2.0.7
  rxdart: ^0.28.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

